#!/usr/bin/env node

/**
 * PostInstall Script for LogDock SDK
 *
 * このスクリプトは npm install 後に自動実行され、
 * プロジェクトのlibディレクトリにlogger.tsファイルを生成します。
 */

const fs = require('fs');
const path = require('path');

// 色付きコンソール出力
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[36m',
  red: '\x1b[31m'
};

const log = {
  info: (msg) => console.log(`${colors.blue}[LogDock]${colors.reset} ${msg}`),
  success: (msg) => console.log(`${colors.green}[LogDock]${colors.reset} ✓ ${msg}`),
  warn: (msg) => console.log(`${colors.yellow}[LogDock]${colors.reset} ⚠ ${msg}`),
  error: (msg) => console.error(`${colors.red}[LogDock]${colors.reset} ✗ ${msg}`)
};

// logger.tsテンプレート
const loggerTemplate = `/**
 * LogDock Logger Configuration
 * Auto-generated by @tora29/logdock-client
 *
 * このファイルは npm install 時に自動生成されました。
 * 必要に応じて設定を調整してください。
 */

import { createLogger } from '@tora29/logdock-client';

// 環境変数または直接指定で設定
const config = {
  // LogDock API URL
  apiUrl: process.env.LOGDOCK_API_URL || 'http://localhost:8080',

  // API Key (必須)
  apiKey: process.env.LOGDOCK_API_KEY || 'your-api-key-here',

  // Application名 (必須)
  app: process.env.LOGDOCK_APP_NAME || 'my-app',

  // デフォルトユーザーID
  defaultUserId: process.env.LOGDOCK_DEFAULT_USER_ID || 'system',

  // デバッグモード
  debug: process.env.LOGDOCK_DEBUG === 'true',

  // Cloudflare Access設定（必要な場合）
  cfAccessClientId: process.env.CF_ACCESS_CLIENT_ID,
  cfAccessClientSecret: process.env.CF_ACCESS_CLIENT_SECRET,

  // 動的にユーザーIDを取得する場合（例：Next.jsのセッション）
  // getUserId: async () => {
  //   // セッションやContextからユーザーIDを取得
  //   // const session = await getSession();
  //   // return session?.user?.id;
  //   return undefined;
  // }
};

// シングルトンインスタンスをエクスポート
export const logger = createLogger(config);

// 名前付きエクスポートで個別メソッドも公開
export const { debug, info, warn, error } = {
  debug: logger.debug.bind(logger),
  info: logger.info.bind(logger),
  warn: logger.warn.bind(logger),
  error: logger.error.bind(logger),
};

// 使用例:
// import { logger } from '@/lib/logger';
// logger.info('Application started');
// logger.error('Payment failed', 'user-123', { amount: 100, currency: 'USD' });
//
// または
// import { info, error } from '@/lib/logger';
// info('Application started');
// error('Payment failed', 'user-123', { amount: 100, currency: 'USD' });
`;

// .envテンプレート
const envTemplate = `
# LogDock Configuration
LOGDOCK_API_URL=http://localhost:8080
LOGDOCK_API_KEY=your-api-key-here
LOGDOCK_APP_NAME=my-app
LOGDOCK_DEFAULT_USER_ID=system
LOGDOCK_DEBUG=false

# Cloudflare Access (if needed)
# CF_ACCESS_CLIENT_ID=your-client-id
# CF_ACCESS_CLIENT_SECRET=your-client-secret
`;

function main() {
  try {
    // プロジェクトのルートディレクトリを検出
    const projectRoot = process.env.INIT_CWD || process.cwd();

    // Skip if running in LogDock SDK itself
    if (projectRoot.includes('logdock-client') || projectRoot.includes('/sdk/typescript')) {
      log.info('Skipping postinstall in SDK development environment');
      return;
    }

    log.info('Setting up LogDock logger...');

    // libディレクトリのパス
    const libDir = path.join(projectRoot, 'lib');
    const loggerFile = path.join(libDir, 'logger.ts');
    const envFile = path.join(projectRoot, '.env.local');
    const envExampleFile = path.join(projectRoot, '.env.example');

    // libディレクトリが存在するか確認
    if (!fs.existsSync(libDir)) {
      // libディレクトリを作成
      fs.mkdirSync(libDir, { recursive: true });
      log.success('Created lib directory');
    }

    // logger.tsファイルが既に存在するか確認
    if (fs.existsSync(loggerFile)) {
      log.warn('logger.ts already exists in lib directory - skipping generation');
      log.info('To regenerate, delete lib/logger.ts and run: npx @tora29/logdock-client init');
    } else {
      // logger.tsファイルを生成
      fs.writeFileSync(loggerFile, loggerTemplate);
      log.success('Generated lib/logger.ts');
    }

    // .env設定の案内
    const hasEnvLocal = fs.existsSync(envFile);
    const hasEnvExample = fs.existsSync(envExampleFile);

    if (!hasEnvLocal && !hasEnvExample) {
      log.info('Adding LogDock environment variables to .env.example...');
      fs.writeFileSync(envExampleFile, envTemplate);
      log.success('Created .env.example with LogDock configuration');
    } else if (hasEnvExample) {
      // .env.exampleが存在する場合、LogDock設定が含まれているか確認
      const envContent = fs.readFileSync(envExampleFile, 'utf8');
      if (!envContent.includes('LOGDOCK_API_KEY')) {
        fs.appendFileSync(envExampleFile, envTemplate);
        log.success('Added LogDock configuration to .env.example');
      }
    }

    // 設定手順を表示
    console.log('');
    log.success('LogDock setup complete!');
    console.log('');
    console.log('Next steps:');
    console.log('1. Configure your LogDock settings in .env.local:');
    console.log(`   ${colors.yellow}LOGDOCK_API_KEY=your-api-key-here${colors.reset}`);
    console.log(`   ${colors.yellow}LOGDOCK_APP_NAME=my-app${colors.reset}`);
    console.log('');
    console.log('2. Import and use the logger in your code:');
    console.log(`   ${colors.green}import { logger } from '@/lib/logger';${colors.reset}`);
    console.log(`   ${colors.green}logger.info('Hello from LogDock!');${colors.reset}`);
    console.log('');
    console.log('Documentation: https://github.com/Tora29/LogDock');
    console.log('');

  } catch (error) {
    log.error(`Failed to generate logger.ts: ${error.message}`);
    // Don't fail the npm install
    process.exit(0);
  }
}

// CLIとして実行された場合
if (require.main === module) {
  main();
}

module.exports = { main };